import * as fs from 'fs/promises';
import * as path from 'path';
import os from 'os';
import { applyAllAgentConfigs } from '../../src/lib';

describe('Jcode Agent Integration', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(
      path.join(os.tmpdir(), 'ruler-jcode-integration-'),
    );
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it('should create AGENTS.md when running ruler apply without MCP config', async () => {
    const rulerDir = path.join(tmpDir, '.ruler');
    await fs.mkdir(rulerDir, { recursive: true });

    await fs.writeFile(
      path.join(rulerDir, 'AGENTS.md'),
      '# Test Rules\n\nThese are test rules for the Jcode agent.',
    );

    await applyAllAgentConfigs(
      tmpDir,
      ['jcode'],
      undefined,
      true,
      undefined,
      false,
      false,
      false,
      true,
    );

    const agentsPath = path.join(tmpDir, 'AGENTS.md');
    const content = await fs.readFile(agentsPath, 'utf8');

    expect(content).toContain('<!-- Generated by Ruler -->');
    expect(content).toContain('These are test rules for the Jcode agent.');
  });

  it('should create .jcode/mcp.json with MCP servers when MCP config exists', async () => {
    const rulerDir = path.join(tmpDir, '.ruler');
    await fs.mkdir(rulerDir, { recursive: true });

    await fs.writeFile(
      path.join(rulerDir, 'AGENTS.md'),
      '# Test Rules\n\nThese are test rules for the Jcode agent.',
    );

    const rulerToml = `
[mcp]
enabled = true

[mcp_servers.test-server]
command = "echo"
args = ["hello"]
`;
    await fs.writeFile(path.join(rulerDir, 'ruler.toml'), rulerToml);

    await applyAllAgentConfigs(
      tmpDir,
      ['jcode'],
      undefined,
      true,
      undefined,
      false,
      false,
      false,
      true,
    );

    const jcodeMcpPath = path.join(tmpDir, '.jcode', 'mcp.json');
    const content = await fs.readFile(jcodeMcpPath, 'utf8');
    const config = JSON.parse(content);

    expect(config.mcpServers['test-server']).toEqual({
      command: 'echo',
      args: ['hello'],
      type: 'stdio',
    });
  });

  it('should filter out remote MCP servers for stdio-only Jcode', async () => {
    const rulerDir = path.join(tmpDir, '.ruler');
    await fs.mkdir(rulerDir, { recursive: true });

    await fs.writeFile(
      path.join(rulerDir, 'AGENTS.md'),
      '# Test Rules\n\nJcode MCP filtering test.',
    );

    const rulerToml = `
[mcp]
enabled = true

[mcp_servers.stdio-server]
command = "echo"
args = ["hello"]

[mcp_servers.remote-server]
type = "http"
url = "https://api.example.com"
`;
    await fs.writeFile(path.join(rulerDir, 'ruler.toml'), rulerToml);

    await applyAllAgentConfigs(
      tmpDir,
      ['jcode'],
      undefined,
      true,
      undefined,
      false,
      false,
      false,
      true,
    );

    const jcodeMcpPath = path.join(tmpDir, '.jcode', 'mcp.json');
    const content = await fs.readFile(jcodeMcpPath, 'utf8');
    const config = JSON.parse(content);

    expect(config.mcpServers['stdio-server']).toBeDefined();
    expect(config.mcpServers['remote-server']).toEqual({
      command: 'npx',
      args: ['-y', 'mcp-remote@latest', 'https://api.example.com'],
    });
  });
});
