import * as fs from 'fs/promises';
import * as path from 'path';
import { setupTestProject, teardownTestProject, runRuler } from '../harness';

describe('MCP provenance', () => {
  it('reverts generated MCP configs when backup and gitignore tracking are disabled', async () => {
    const project = await setupTestProject({
      '.ruler/ruler.toml': [
        '[gitignore]',
        'enabled = false',
        '',
        '[backup]',
        'enabled = false',
        '',
        '[mcp_servers.generated]',
        'command = "node"',
        'args = ["server.js"]',
        '',
      ].join('\n'),
    });
    const mcpPath = path.join(project.projectRoot, '.cursor', 'mcp.json');
    const provenancePath = `${mcpPath}.ruler-generated`;

    try {
      runRuler('apply --agents cursor', project.projectRoot);

      await expect(fs.access(mcpPath)).resolves.toBeUndefined();
      await expect(fs.access(provenancePath)).resolves.toBeUndefined();
      await expect(
        fs.access(path.join(project.projectRoot, '.gitignore')),
      ).rejects.toThrow();

      runRuler('revert --agents cursor', project.projectRoot);

      await expect(fs.access(mcpPath)).rejects.toThrow();
      await expect(fs.access(provenancePath)).rejects.toThrow();
    } finally {
      await teardownTestProject(project.projectRoot);
    }
  });

  it('does not treat unmarked MCP sidecars as generated provenance', async () => {
    const project = await setupTestProject({
      '.ruler/ruler.toml': '[mcp_servers.generated]\ncommand = "node"\n',
      '.cursor/mcp.json': '{"mcpServers":{}}',
      '.cursor/mcp.json.ruler-generated': 'not generated by Ruler',
    });
    const mcpPath = path.join(project.projectRoot, '.cursor', 'mcp.json');
    const provenancePath = `${mcpPath}.ruler-generated`;

    try {
      runRuler('revert --agents cursor', project.projectRoot);

      await expect(fs.access(mcpPath)).resolves.toBeUndefined();
      await expect(fs.access(provenancePath)).resolves.toBeUndefined();
    } finally {
      await teardownTestProject(project.projectRoot);
    }
  });

  it('reverts generated Gemini settings when backup and gitignore tracking are disabled', async () => {
    const project = await setupTestProject({
      '.ruler/ruler.toml': [
        '[gitignore]',
        'enabled = false',
        '',
        '[backup]',
        'enabled = false',
        '',
        '[mcp_servers.generated]',
        'command = "node"',
        'args = ["server.js"]',
        '',
      ].join('\n'),
    });
    const settingsPath = path.join(
      project.projectRoot,
      '.gemini',
      'settings.json',
    );
    const provenancePath = `${settingsPath}.ruler-generated`;

    try {
      runRuler('apply --agents gemini', project.projectRoot);

      await expect(fs.access(settingsPath)).resolves.toBeUndefined();
      await expect(fs.access(provenancePath)).resolves.toBeUndefined();
      await expect(
        fs.access(path.join(project.projectRoot, '.gitignore')),
      ).rejects.toThrow();

      runRuler('revert --agents gemini', project.projectRoot);

      await expect(fs.access(settingsPath)).rejects.toThrow();
      await expect(fs.access(provenancePath)).rejects.toThrow();
    } finally {
      await teardownTestProject(project.projectRoot);
    }
  });

  it('reverts generated RooCode MCP config when backup and gitignore tracking are disabled', async () => {
    const project = await setupTestProject({
      '.ruler/ruler.toml': [
        '[gitignore]',
        'enabled = false',
        '',
        '[backup]',
        'enabled = false',
        '',
        '[mcp_servers.generated]',
        'command = "node"',
        'args = ["server.js"]',
        '',
      ].join('\n'),
    });
    const mcpPath = path.join(project.projectRoot, '.roo', 'mcp.json');
    const provenancePath = `${mcpPath}.ruler-generated`;

    try {
      runRuler('apply --agents roo', project.projectRoot);

      await expect(fs.access(mcpPath)).resolves.toBeUndefined();
      await expect(fs.access(provenancePath)).resolves.toBeUndefined();
      await expect(
        fs.access(path.join(project.projectRoot, '.gitignore')),
      ).rejects.toThrow();

      runRuler('revert --agents roo', project.projectRoot);

      await expect(fs.access(mcpPath)).rejects.toThrow();
      await expect(fs.access(provenancePath)).rejects.toThrow();
    } finally {
      await teardownTestProject(project.projectRoot);
    }
  });
});
