import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";
import { readMarkdownFiles } from "../../../src/core/FileSystemUtils";

describe("AGENTS.md duplicate content prevention", () => {
	let tmpDir: string;
	let skillerDir: string;

	beforeEach(async () => {
		tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "skiller-test-"));
		skillerDir = path.join(tmpDir, ".claude");
		await fs.mkdir(skillerDir, { recursive: true });
	});

	afterEach(async () => {
		await fs.rm(tmpDir, { recursive: true, force: true });
	});

	it("should include root AGENTS.md when no marker is present", async () => {
		// Create a .claude/instructions.md file
		const skillerInstructions = "These are skiller instructions.";
		await fs.writeFile(
			path.join(skillerDir, "instructions.md"),
			skillerInstructions,
		);

		// Create a root AGENTS.md file without marker
		const rootAgentsContent = "This is root AGENTS.md content.";
		await fs.writeFile(path.join(tmpDir, "AGENTS.md"), rootAgentsContent);

		const files = await readMarkdownFiles(skillerDir);

		// Should include both files
		expect(files).toHaveLength(2);
		expect(files[0].content).toBe(rootAgentsContent);
		expect(files[1].content).toBe(skillerInstructions);
	});

	it("should skip root AGENTS.md when marker is present and .claude has files", async () => {
		// Create a .claude/instructions.md file
		const skillerInstructions = "These are skiller instructions.";
		await fs.writeFile(
			path.join(skillerDir, "instructions.md"),
			skillerInstructions,
		);

		// Create a root AGENTS.md file WITH marker
		const rootAgentsContent =
			"<!-- Generated by Skiller -->\nThis is generated content.";
		await fs.writeFile(path.join(tmpDir, "AGENTS.md"), rootAgentsContent);

		const files = await readMarkdownFiles(skillerDir);

		// Should only include the .claude file, skip the generated root AGENTS.md
		expect(files).toHaveLength(1);
		expect(files[0].content).toBe(skillerInstructions);
	});

	it("should include root AGENTS.md with marker when .claude has no files", async () => {
		// Create a root AGENTS.md file WITH marker but no .claude files
		const rootAgentsContent =
			"<!-- Generated by Skiller -->\nThis is generated content.";
		await fs.writeFile(path.join(tmpDir, "AGENTS.md"), rootAgentsContent);

		const files = await readMarkdownFiles(skillerDir);

		// Should include the root AGENTS.md since there are no .claude files
		expect(files).toHaveLength(1);
		expect(files[0].content).toBe(rootAgentsContent);
	});

	it("should include root AGENTS.md with marker when inside .claude directory", async () => {
		// Create AGENTS.md inside .claude directory with marker
		const agentsContent =
			"<!-- Generated by Skiller -->\nInside skiller directory.";
		await fs.writeFile(path.join(skillerDir, "AGENTS.md"), agentsContent);

		const files = await readMarkdownFiles(skillerDir);

		// Should include the .claude/AGENTS.md file
		expect(files).toHaveLength(1);
		expect(files[0].content).toBe(agentsContent);
	});
});
