import * as fs from 'fs/promises';
import * as path from 'path';
import os from 'os';
import {
  backupFile,
  findRulerDir,
  readMarkdownFiles,
  writeGeneratedFile,
} from '../../../src/core/FileSystemUtils';

describe('FileSystemUtils', () => {
  let tmpDir: string;
  beforeAll(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-test-'));
  });
  afterAll(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  describe('findRulerDir', () => {
    it('finds .ruler in parent directories', async () => {
      const projectDir = path.join(tmpDir, 'project');
      const rulerDir = path.join(projectDir, '.ruler');
      const nestedDir = path.join(projectDir, 'sub', 'child');
      await fs.mkdir(rulerDir, { recursive: true });
      await fs.mkdir(nestedDir, { recursive: true });
      const found = await findRulerDir(nestedDir);
      expect(found).toBe(rulerDir);
    });

    it('returns null if .ruler is not found', async () => {
      const someDir = path.join(tmpDir, 'nofile');
      await fs.mkdir(someDir, { recursive: true });
      const found = await findRulerDir(someDir, false); // Don't check global config
      expect(found).toBeNull();
    });

    it('does not log an error when optional global config is absent', async () => {
      const originalXdgConfigHome = process.env.XDG_CONFIG_HOME;
      const xdgConfigHome = path.join(tmpDir, 'missing-global-config');
      process.env.XDG_CONFIG_HOME = xdgConfigHome;
      const consoleErrorSpy = jest
        .spyOn(console, 'error')
        .mockImplementation(() => {});

      try {
        const projectDir = path.join(tmpDir, 'project-without-ruler');
        await fs.mkdir(projectDir, { recursive: true });

        const found = await findRulerDir(projectDir, true);

        expect(found).toBeNull();
        expect(consoleErrorSpy).not.toHaveBeenCalled();
      } finally {
        consoleErrorSpy.mockRestore();
        if (originalXdgConfigHome === undefined) {
          delete process.env.XDG_CONFIG_HOME;
        } else {
          process.env.XDG_CONFIG_HOME = originalXdgConfigHome;
        }
      }
    });
  });

  describe('backupFile', () => {
    it('does not overwrite an existing backup', async () => {
      const filePath = path.join(tmpDir, 'backup-target.txt');

      await fs.writeFile(filePath, 'original');
      await backupFile(filePath);
      await fs.writeFile(filePath, 'generated');
      await backupFile(filePath);

      await expect(fs.readFile(`${filePath}.bak`, 'utf8')).resolves.toBe(
        'original',
      );
    });

    it('refuses to back up a symlinked output file', async () => {
      const outsidePath = path.join(tmpDir, 'backup-outside.txt');
      const linkPath = path.join(tmpDir, 'backup-link.txt');
      await fs.writeFile(outsidePath, 'outside');
      await fs.symlink(outsidePath, linkPath);

      await expect(backupFile(linkPath)).rejects.toThrow(
        'Refusing to back up symlinked file',
      );
      await expect(fs.stat(`${linkPath}.bak`)).rejects.toThrow();
    });

    it('does not back up an existing Ruler-generated file', async () => {
      const filePath = path.join(tmpDir, 'generated-backup-target.txt');
      await fs.writeFile(filePath, '<!-- Generated by Ruler -->\ngenerated');

      await backupFile(filePath);

      await expect(fs.stat(`${filePath}.bak`)).rejects.toThrow();
    });
  });

  describe('writeGeneratedFile', () => {
    it('refuses to write through a symlinked output file', async () => {
      const outsidePath = path.join(tmpDir, 'write-outside.txt');
      const linkPath = path.join(tmpDir, 'write-link.txt');
      await fs.writeFile(outsidePath, 'outside');
      await fs.symlink(outsidePath, linkPath);

      await expect(writeGeneratedFile(linkPath, 'generated')).rejects.toThrow(
        'Refusing to write generated file through symlink',
      );
      await expect(fs.readFile(outsidePath, 'utf8')).resolves.toBe('outside');
    });
  });

  describe('readMarkdownFiles', () => {
    it('reads and sorts markdown files', async () => {
      const rulerDir = path.join(tmpDir, '.ruler2');
      const subDir = path.join(rulerDir, 'sub');
      await fs.mkdir(subDir, { recursive: true });
      const fileA = path.join(rulerDir, 'a.md');
      const fileB = path.join(subDir, 'b.md');
      await fs.writeFile(fileA, 'contentA');
      await fs.writeFile(fileB, 'contentB');
      const files = await readMarkdownFiles(rulerDir);
      expect(files.map((f) => f.path)).toEqual([fileA, fileB]);
      expect(files[0].content).toBe('contentA');
      expect(files[1].content).toBe('contentB');
    });

    it('skips symlinked markdown files outside .ruler', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-symlink-file');
      await fs.mkdir(rulerDir, { recursive: true });
      const realFile = path.join(tmpDir, 'external.md');
      await fs.writeFile(realFile, 'symlinked content');
      const linkPath = path.join(rulerDir, 'linked.md');
      await fs.symlink(realFile, linkPath);
      const files = await readMarkdownFiles(rulerDir);
      expect(files.map((f) => f.path)).not.toContain(linkPath);
    });

    it('reads symlinked markdown files inside .ruler', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-internal-symlink-file');
      await fs.mkdir(path.join(rulerDir, 'real'), { recursive: true });
      const realFile = path.join(rulerDir, 'real', 'source.md');
      await fs.writeFile(realFile, 'internal symlinked content');
      const linkPath = path.join(rulerDir, 'linked.md');
      await fs.symlink(realFile, linkPath);

      const files = await readMarkdownFiles(rulerDir);

      expect(files.map((f) => f.path)).toContain(linkPath);
      const linked = files.find((f) => f.path === linkPath);
      expect(linked?.content).toBe('internal symlinked content');
    });

    it('skips symlinked directories outside .ruler', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-symlink-dir');
      await fs.mkdir(rulerDir, { recursive: true });
      const realDir = path.join(tmpDir, 'external-dir');
      await fs.mkdir(realDir, { recursive: true });
      const realFile = path.join(realDir, 'deep.md');
      await fs.writeFile(realFile, 'deep content');
      const linkPath = path.join(rulerDir, 'linked-dir');
      await fs.symlink(realDir, linkPath);
      const files = await readMarkdownFiles(rulerDir);
      const deepFile = path.join(linkPath, 'deep.md');
      expect(files.map((f) => f.path)).not.toContain(deepFile);
    });

    it('follows symlinked directories inside .ruler', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-internal-symlink-dir');
      await fs.mkdir(rulerDir, { recursive: true });
      const realDir = path.join(rulerDir, 'real-dir');
      await fs.mkdir(realDir, { recursive: true });
      const realFile = path.join(realDir, 'deep.md');
      await fs.writeFile(realFile, 'deep content');
      const linkPath = path.join(rulerDir, 'linked-dir');
      await fs.symlink(realDir, linkPath);

      const files = await readMarkdownFiles(rulerDir);
      const deepFile = path.join(linkPath, 'deep.md');

      expect(files.map((f) => f.path)).toContain(deepFile);
      const deep = files.find((f) => f.path === deepFile);
      expect(deep?.content).toBe('deep content');
    });

    it('does not recurse through symlink cycles', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-symlink-cycle');
      await fs.mkdir(rulerDir, { recursive: true });
      await fs.writeFile(path.join(rulerDir, 'rules.md'), 'content');
      await fs.symlink(rulerDir, path.join(rulerDir, 'self'));

      const files = await readMarkdownFiles(rulerDir);

      expect(files.map((f) => path.relative(rulerDir, f.path))).toEqual([
        'rules.md',
      ]);
    });

    it('skips broken symlinks gracefully', async () => {
      const rulerDir = path.join(tmpDir, '.ruler-broken-symlink');
      await fs.mkdir(rulerDir, { recursive: true });
      const linkPath = path.join(rulerDir, 'broken.md');
      await fs.symlink('/nonexistent/path/file.md', linkPath);
      const files = await readMarkdownFiles(rulerDir);
      expect(files.map((f) => f.path)).not.toContain(linkPath);
    });

    it('skips root AGENTS.md when it is a symlink outside the repository', async () => {
      const projectDir = path.join(tmpDir, 'root-agents-outside-link');
      const rulerDir = path.join(projectDir, '.ruler');
      const outsidePath = path.join(tmpDir, 'external-root-agents.md');
      const rootAgentsPath = path.join(projectDir, 'AGENTS.md');
      await fs.mkdir(rulerDir, { recursive: true });
      await fs.writeFile(path.join(rulerDir, 'AGENTS.md'), 'ruler content');
      await fs.writeFile(outsidePath, 'external root content');
      await fs.symlink(outsidePath, rootAgentsPath);

      const files = await readMarkdownFiles(rulerDir);

      expect(files.map((f) => f.path)).not.toContain(rootAgentsPath);
      expect(files.map((f) => f.content)).not.toContain(
        'external root content',
      );
      expect(files.map((f) => f.content)).toContain('ruler content');
    });
  });
});
