import * as fs from 'fs/promises';
import * as path from 'path';
import os from 'os';

import {
  revertAgentConfiguration,
  cleanUpAuxiliaryFiles,
} from '../../../src/core/revert-engine';
import { IAgent } from '../../../src/agents/IAgent';
import { IAgentConfig } from '../../../src/core/ConfigLoader';

const GENERATED_MARKER = '<!-- Generated by Ruler -->';

async function writeRulerGitignore(
  tmpDir: string,
  paths: string[],
): Promise<void> {
  await fs.writeFile(
    path.join(tmpDir, '.gitignore'),
    [
      '# START Ruler Generated Files',
      ...paths.map((filePath) => `/${filePath}`),
      '# END Ruler Generated Files',
      '',
    ].join('\n'),
  );
}

// Mock agent for testing
class MockAgent implements IAgent {
  constructor(
    private name: string,
    private identifier: string,
  ) {}

  getName(): string {
    return this.name;
  }

  getIdentifier(): string {
    return this.identifier;
  }

  async applyRulerConfig(
    rules: string,
    projectRoot: string,
    mcpJson: Record<string, unknown> | null,
    agentConfig?: any,
  ): Promise<void> {
    // Mock implementation
  }

  getDefaultOutputPath(projectRoot: string): string {
    return `${projectRoot}/.${this.identifier}/config.json`;
  }

  getMcpServerKey?(): string {
    return 'mcpServers';
  }
}

class MockOpenHandsAgent extends MockAgent {
  constructor() {
    super('Open Hands', 'openhands');
  }

  getDefaultOutputPath(projectRoot: string): string {
    return path.join(projectRoot, '.openhands', 'microagents', 'repo.md');
  }
}

describe('revert-engine', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-revert-engine-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  describe('revertAgentConfiguration', () => {
    it('should restore files from backup when backup exists', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');
      const backupPath = `${configPath}.bak`;

      // Create directories and files
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, 'current content');
      await fs.writeFile(backupPath, 'backup content');

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(1);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(1);

      // Check that file was restored
      const restoredContent = await fs.readFile(configPath, 'utf8');
      expect(restoredContent).toBe('backup content');

      // Check that backup was removed
      const backupExists = await fs
        .access(backupPath)
        .then(() => true)
        .catch(() => false);
      expect(backupExists).toBe(false);
    });

    it('should remove marker-bearing generated files when no backup exists', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');

      // Create directories and file (no backup)
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, `${GENERATED_MARKER}\ngenerated content`);

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(0);
      expect(result.removed).toBe(1);
      expect(result.backupsRemoved).toBe(0);

      // Check that file was removed
      const fileExists = await fs
        .access(configPath)
        .then(() => true)
        .catch(() => false);
      expect(fileExists).toBe(false);
    });

    it('should remove source-marked global generated files when no backup exists', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');

      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(
        configPath,
        '\n\n<!-- Source: ruler/AGENTS.md -->\n\ngenerated content\n',
      );

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(0);
      expect(result.removed).toBe(1);
      expect(result.backupsRemoved).toBe(0);

      const fileExists = await fs
        .access(configPath)
        .then(() => true)
        .catch(() => false);
      expect(fileExists).toBe(false);
    });

    it('should preserve unmarked files when no backup exists', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');
      const originalContent = 'user-owned content';

      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, originalContent);

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(0);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(0);
      await expect(fs.readFile(configPath, 'utf8')).resolves.toBe(
        originalContent,
      );
    });

    it('should keep consumed backups when keepBackups is true', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');
      const backupPath = `${configPath}.bak`;

      // Create directories and files
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, 'current content');
      await fs.writeFile(backupPath, 'backup content');

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        true, // keepBackups
        false,
        false,
      );

      expect(result.restored).toBe(1);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(0);

      // keepBackups preserves the restored backup for inspection.
      const backupExists = await fs
        .access(backupPath)
        .then(() => true)
        .catch(() => false);
      expect(backupExists).toBe(true);
    });

    it('should handle dry run mode', async () => {
      const agent = new MockAgent('Claude Code', 'claude');
      const configPath = path.join(tmpDir, '.claude', 'config.json');
      const backupPath = `${configPath}.bak`;

      // Create directories and files
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, 'current content');
      await fs.writeFile(backupPath, 'backup content');

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        true, // dryRun
      );

      expect(result.restored).toBe(1);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(1);

      // Check that files were not actually modified in dry run
      const currentContent = await fs.readFile(configPath, 'utf8');
      expect(currentContent).toBe('current content');

      const backupExists = await fs
        .access(backupPath)
        .then(() => true)
        .catch(() => false);
      expect(backupExists).toBe(true);
    });

    it('should handle non-existent files gracefully', async () => {
      const agent = new MockAgent('Claude Code', 'claude');

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(0);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(0);
    });

    it('should preserve Open Hands root config.toml when no backup exists', async () => {
      const agent = new MockOpenHandsAgent();
      const configPath = path.join(tmpDir, 'config.toml');
      const originalContent = '[core]\nworkspace_base = "/tmp/project"\n';

      await fs.writeFile(configPath, originalContent);

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(0);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(0);
      await expect(fs.readFile(configPath, 'utf8')).resolves.toBe(
        originalContent,
      );
    });

    it('should restore Open Hands root config.toml from backup when backup exists', async () => {
      const agent = new MockOpenHandsAgent();
      const configPath = path.join(tmpDir, 'config.toml');
      const backupPath = `${configPath}.bak`;

      await fs.writeFile(configPath, '[mcp]\nstdio_servers = []\n');
      await fs.writeFile(
        backupPath,
        '[core]\nworkspace_base = "/tmp/project"\n',
      );

      const result = await revertAgentConfiguration(
        agent,
        tmpDir,
        undefined,
        false,
        false,
        false,
      );

      expect(result.restored).toBe(1);
      expect(result.removed).toBe(0);
      expect(result.backupsRemoved).toBe(1);
      await expect(fs.readFile(configPath, 'utf8')).resolves.toBe(
        '[core]\nworkspace_base = "/tmp/project"\n',
      );
      await expect(fs.access(backupPath)).rejects.toThrow();
    });
  });

  describe('cleanUpAuxiliaryFiles', () => {
    it('should remove additional files and empty directories', async () => {
      // Create some test directories and files
      const geminiDir = path.join(tmpDir, '.gemini');
      const geminiSettings = path.join(geminiDir, 'settings.json');
      const mcpFile = path.join(tmpDir, '.mcp.json');
      const junieMcpDir = path.join(tmpDir, '.junie', 'mcp');
      const junieMcpFile = path.join(junieMcpDir, 'mcp.json');

      await fs.mkdir(geminiDir, { recursive: true });
      await fs.mkdir(junieMcpDir, { recursive: true });
      await fs.writeFile(geminiSettings, '{}');
      await fs.writeFile(mcpFile, '{}');
      await fs.writeFile(junieMcpFile, '{}');
      await writeRulerGitignore(tmpDir, [
        '.gemini/settings.json',
        '.mcp.json',
        '.junie/mcp/mcp.json',
      ]);

      const result = await cleanUpAuxiliaryFiles(tmpDir, false, false);

      expect(result.additionalFilesRemoved).toBeGreaterThan(0);
      expect(result.directoriesRemoved).toBeGreaterThan(0);
      await expect(fs.access(junieMcpFile)).rejects.toThrow();
    });

    it('should handle dry run mode', async () => {
      // Create some test files
      const mcpFile = path.join(tmpDir, '.mcp.json');
      await fs.writeFile(mcpFile, '{}');
      await writeRulerGitignore(tmpDir, ['.mcp.json']);

      const result = await cleanUpAuxiliaryFiles(tmpDir, false, true);

      expect(result.additionalFilesRemoved).toBeGreaterThan(0);

      // Check that file still exists in dry run
      const fileExists = await fs
        .access(mcpFile)
        .then(() => true)
        .catch(() => false);
      expect(fileExists).toBe(true);
    });

    it('should handle non-existent files gracefully', async () => {
      const result = await cleanUpAuxiliaryFiles(tmpDir, false, false);

      expect(result.additionalFilesRemoved).toBeGreaterThanOrEqual(0);
      expect(result.directoriesRemoved).toBeGreaterThanOrEqual(0);
    });

    it('should preserve root config.toml during auxiliary cleanup when no backup exists', async () => {
      const configPath = path.join(tmpDir, 'config.toml');
      const originalContent = '[core]\nworkspace_base = "/tmp/project"\n';

      await fs.writeFile(configPath, originalContent);

      const result = await cleanUpAuxiliaryFiles(tmpDir, false, false);

      expect(result.additionalFilesRemoved).toBe(0);
      await expect(fs.readFile(configPath, 'utf8')).resolves.toBe(
        originalContent,
      );
    });

    it('should preserve unmarked additional files when no backup exists', async () => {
      const mcpFile = path.join(tmpDir, '.mcp.json');
      const originalContent = '{"mcpServers": {"user": {"command": "node"}}}';

      await fs.writeFile(mcpFile, originalContent);

      const result = await cleanUpAuxiliaryFiles(tmpDir, false, false);

      expect(result.additionalFilesRemoved).toBe(0);
      await expect(fs.readFile(mcpFile, 'utf8')).resolves.toBe(originalContent);
    });
  });

  describe('dry-run logging patterns', () => {
    beforeEach(() => {
      jest.clearAllMocks();
    });

    it('should use [ruler:dry-run] prefix when dryRun is true', async () => {
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      // Create a test file to trigger removal in removeAdditionalAgentFiles
      const mcpFile = path.join(tmpDir, '.mcp.json');
      await fs.writeFile(mcpFile, '{}');
      await writeRulerGitignore(tmpDir, ['.mcp.json']);

      await cleanUpAuxiliaryFiles(tmpDir, true, true); // verbose=true, dryRun=true

      const errorCalls = consoleErrorSpy.mock.calls.flat();
      const hasRulerDryRunPrefix = errorCalls.some(
        (call) => typeof call === 'string' && call.includes('[ruler:dry-run]'),
      );

      expect(hasRulerDryRunPrefix).toBe(true);
      consoleErrorSpy.mockRestore();
    });

    it('uses prefix string for verbose dry-run VSCode settings cleanup logs', async () => {
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();
      const settingsPath = path.join(tmpDir, '.vscode', 'settings.json');

      await fs.mkdir(path.dirname(settingsPath), { recursive: true });
      await fs.writeFile(
        settingsPath,
        JSON.stringify({
          'augment.advanced': {
            mcpServers: [{ name: 'test-server', command: 'test' }],
          },
        }),
      );

      await cleanUpAuxiliaryFiles(tmpDir, true, true);

      const errorCalls = consoleErrorSpy.mock.calls.flat();

      expect(errorCalls).toContain(
        `[ruler:verbose] [ruler:dry-run] Would remove empty VSCode settings file`,
      );
      expect(
        errorCalls.some(
          (call) =>
            typeof call === 'string' && call.includes('function actionPrefix'),
        ),
      ).toBe(false);
      consoleErrorSpy.mockRestore();
    });

    it('should use [ruler] prefix when dryRun is false', async () => {
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      // Create a test file to trigger removal in removeAdditionalAgentFiles
      const mcpFile = path.join(tmpDir, '.mcp.json');
      await fs.writeFile(mcpFile, '{}');
      await writeRulerGitignore(tmpDir, ['.mcp.json']);

      await cleanUpAuxiliaryFiles(tmpDir, true, false); // verbose=true, dryRun=false

      const errorCalls = consoleErrorSpy.mock.calls.flat();
      const hasRulerPrefix = errorCalls.some(
        (call) =>
          typeof call === 'string' &&
          call.includes('[ruler]') &&
          !call.includes('[ruler:dry-run]'),
      );

      expect(hasRulerPrefix).toBe(true);
      consoleErrorSpy.mockRestore();
    });
  });
});
