import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { revertAllAgentConfigs } from '../../../src/revert';

const GENERATED_MARKER = '<!-- Generated by Ruler -->';

describe('Revert Core Functions', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-revert-unit-'));

    const rulerDir = path.join(tmpDir, '.ruler');
    await fs.mkdir(rulerDir, { recursive: true });
    await fs.writeFile(path.join(rulerDir, 'instructions.md'), 'Test Rule');
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  describe('revertAllAgentConfigs', () => {
    it('should throw error when .ruler directory not found', async () => {
      const emptyDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-empty-'));

      try {
        await expect(
          revertAllAgentConfigs(
            emptyDir,
            undefined,
            undefined,
            false,
            false,
            false,
            true,
          ),
        ).rejects.toThrow('.ruler directory not found');
      } finally {
        await fs.rm(emptyDir, { recursive: true, force: true });
      }
    });

    it('should handle dry-run mode correctly', async () => {
      await fs.writeFile(
        path.join(tmpDir, 'CLAUDE.md'),
        `${GENERATED_MARKER}\nGenerated content`,
      );

      const consoleSpy = jest.spyOn(console, 'log').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        true,
      );

      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('[ruler:dry-run] Revert summary (dry run):'),
      );

      await expect(
        fs.access(path.join(tmpDir, 'CLAUDE.md')),
      ).resolves.toBeUndefined();

      consoleSpy.mockRestore();
    });

    it('should handle verbose logging', async () => {
      const consoleSpy = jest.spyOn(console, 'log').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        true,
        false,
      );

      expect(consoleSpy).toHaveBeenCalled();

      consoleSpy.mockRestore();
    });

    it('should handle specific agents filter', async () => {
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Claude content');
      await fs.writeFile(path.join(tmpDir, 'AGENTS.md'), 'Agents content');

      const consoleSpy = jest.spyOn(console, 'log').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        ['claude'],
        undefined,
        false,
        false,
        false,
      );

      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('Reverting Claude Code'),
      );
      expect(consoleSpy).not.toHaveBeenCalledWith(
        expect.stringContaining('Reverting OpenAI Codex CLI'),
      );

      consoleSpy.mockRestore();
    });

    it('continues with valid CLI agents when invalid filters are present', async () => {
      await fs.writeFile(
        path.join(tmpDir, 'CLAUDE.md'),
        `${GENERATED_MARKER}\nClaude content`,
      );

      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        ['claude', 'not-a-real-agent'],
        undefined,
        false,
        true,
        false,
      );

      expect(consoleLogSpy).toHaveBeenCalledWith(
        expect.stringContaining('Reverting Claude Code'),
      );
      expect(consoleErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('continuing with valid agents only'),
      );
      await expect(fs.access(path.join(tmpDir, 'CLAUDE.md'))).rejects.toThrow();

      consoleLogSpy.mockRestore();
      consoleErrorSpy.mockRestore();
    });

    it('uses valid default agents when invalid defaults are present', async () => {
      await fs.writeFile(
        path.join(tmpDir, '.ruler', 'ruler.toml'),
        'default_agents = ["claude", "not-a-real-agent"]\n',
      );
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Claude content');
      await fs.writeFile(path.join(tmpDir, 'AGENTS.md'), 'Agents content');

      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        true,
        false,
      );

      expect(consoleLogSpy).toHaveBeenCalledWith(
        expect.stringContaining('Reverting Claude Code'),
      );
      expect(consoleLogSpy).not.toHaveBeenCalledWith(
        expect.stringContaining('Reverting AgentsMd'),
      );
      expect(consoleErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('continuing with valid agents only'),
      );

      consoleLogSpy.mockRestore();
      consoleErrorSpy.mockRestore();
    });

    it('honors agent config overrides when falling back from invalid defaults', async () => {
      await fs.writeFile(
        path.join(tmpDir, '.ruler', 'ruler.toml'),
        [
          'default_agents = ["claude", "not-a-real-agent"]',
          '',
          '[agents.claude]',
          'enabled = false',
          '',
          '[agents.agentsmd]',
          'enabled = true',
          '',
        ].join('\n'),
      );
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Claude content');
      await fs.writeFile(path.join(tmpDir, 'AGENTS.md'), 'Agents content');

      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        true,
        false,
      );

      expect(consoleLogSpy).not.toHaveBeenCalledWith(
        expect.stringContaining('Reverting Claude Code'),
      );
      expect(consoleLogSpy).toHaveBeenCalledWith(
        expect.stringContaining('Reverting AgentsMd'),
      );

      consoleLogSpy.mockRestore();
      consoleErrorSpy.mockRestore();
    });

    it('should keep consumed backup when keep-backups is true', async () => {
      const filePath = path.join(tmpDir, 'CLAUDE.md');
      const backupPath = `${filePath}.bak`;

      await fs.writeFile(backupPath, 'Original content');
      await fs.writeFile(filePath, 'Modified content');

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        true,
        false,
        false,
      );

      await expect(fs.access(backupPath)).resolves.toBeUndefined();

      const restoredContent = await fs.readFile(filePath, 'utf8');
      expect(restoredContent).toBe('Original content');
    });

    it('should remove backup files when keep-backups is false', async () => {
      const filePath = path.join(tmpDir, 'CLAUDE.md');
      const backupPath = `${filePath}.bak`;

      await fs.writeFile(backupPath, 'Original content');
      await fs.writeFile(filePath, 'Modified content');

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.access(backupPath)).rejects.toThrow();

      const restoredContent = await fs.readFile(filePath, 'utf8');
      expect(restoredContent).toBe('Original content');
    });

    it('should remove generated files without backups', async () => {
      const filePath = path.join(tmpDir, 'CLAUDE.md');
      await fs.writeFile(filePath, `${GENERATED_MARKER}\nGenerated content`);

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.access(filePath)).rejects.toThrow();
    });

    it('should preserve unmarked files without backups', async () => {
      const filePath = path.join(tmpDir, 'CLAUDE.md');
      const originalContent = 'User-authored Claude instructions';
      await fs.writeFile(filePath, originalContent);

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.readFile(filePath, 'utf8')).resolves.toBe(
        originalContent,
      );
    });

    it('should clean up empty directories', async () => {
      const githubDir = path.join(tmpDir, '.github');
      const cursorDir = path.join(tmpDir, '.cursor');

      await fs.mkdir(githubDir, { recursive: true });
      await fs.mkdir(cursorDir, { recursive: true });

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.access(githubDir)).rejects.toThrow();
      await expect(fs.access(cursorDir)).rejects.toThrow();
    });

    it('should preserve non-empty directories', async () => {
      const githubDir = path.join(tmpDir, '.github');
      await fs.mkdir(githubDir, { recursive: true });
      await fs.writeFile(
        path.join(githubDir, 'existing-file.txt'),
        'Existing content',
      );

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.access(githubDir)).resolves.toBeUndefined();
      await expect(
        fs.access(path.join(githubDir, 'existing-file.txt')),
      ).resolves.toBeUndefined();
    });

    it('removes the ruler-managed block from .gitignore', async () => {
      await fs.writeFile(
        path.join(tmpDir, '.gitignore'),
        [
          'node_modules/',
          '',
          '# START Ruler Generated Files',
          '/AGENTS.md',
          '/CLAUDE.md',
          '# END Ruler Generated Files',
          '',
          '*.log',
          '',
        ].join('\n'),
      );

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      const content = await fs.readFile(
        path.join(tmpDir, '.gitignore'),
        'utf8',
      );
      expect(content).toBe('node_modules/\n\n*.log\n');
    });

    it('removes the ruler-managed block from .git/info/exclude', async () => {
      const excludePath = path.join(tmpDir, '.git', 'info', 'exclude');
      await fs.mkdir(path.dirname(excludePath), { recursive: true });
      await fs.writeFile(
        excludePath,
        [
          '*.local',
          '',
          '# START Ruler Generated Files',
          '/AGENTS.md',
          '/CLAUDE.md',
          '# END Ruler Generated Files',
          '',
          '*.secret',
          '',
        ].join('\n'),
      );

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      const content = await fs.readFile(excludePath, 'utf8');
      expect(content).toBe('*.local\n\n*.secret\n');
    });

    it('removes .gitignore when it only contains the ruler-managed block', async () => {
      await fs.writeFile(
        path.join(tmpDir, '.gitignore'),
        [
          '# START Ruler Generated Files',
          '/AGENTS.md',
          '# END Ruler Generated Files',
          '',
        ].join('\n'),
      );

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      );

      await expect(
        fs.access(path.join(tmpDir, '.gitignore')),
      ).rejects.toThrow();
    });

    it('leaves .gitignore unchanged during dry-run cleanup', async () => {
      const gitignoreContent = [
        '# START Ruler Generated Files',
        '/AGENTS.md',
        '# END Ruler Generated Files',
        '',
      ].join('\n');
      await fs.writeFile(path.join(tmpDir, '.gitignore'), gitignoreContent);

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        true,
      );

      await expect(
        fs.readFile(path.join(tmpDir, '.gitignore'), 'utf8'),
      ).resolves.toBe(gitignoreContent);
    });

    it('does not report .gitignore cleanup when no ruler-managed block exists', async () => {
      await fs.writeFile(path.join(tmpDir, '.gitignore'), 'node_modules/\n');

      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();

      try {
        await revertAllAgentConfigs(
          tmpDir,
          undefined,
          undefined,
          false,
          false,
          false,
        );

        expect(consoleLogSpy).not.toHaveBeenCalledWith(
          '  .gitignore cleaned: yes',
        );
        await expect(
          fs.readFile(path.join(tmpDir, '.gitignore'), 'utf8'),
        ).resolves.toBe('node_modules/\n');
      } finally {
        consoleLogSpy.mockRestore();
      }
    });

    it('leaves .gitignore unchanged when the only end marker appears before the start marker', async () => {
      const gitignoreContent = [
        'node_modules/',
        '# END Ruler Generated Files',
        'important-user-pattern',
        '# START Ruler Generated Files',
        'another-user-pattern',
        '',
      ].join('\n');
      await fs.writeFile(path.join(tmpDir, '.gitignore'), gitignoreContent);

      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();

      try {
        await revertAllAgentConfigs(
          tmpDir,
          undefined,
          undefined,
          false,
          false,
          false,
        );

        expect(consoleLogSpy).not.toHaveBeenCalledWith(
          '  .gitignore cleaned: yes',
        );
        await expect(
          fs.readFile(path.join(tmpDir, '.gitignore'), 'utf8'),
        ).resolves.toBe(gitignoreContent);
      } finally {
        consoleLogSpy.mockRestore();
      }
    });

    it('recognises generated files listed in the real worktree exclude file', async () => {
      const actualGitDir = path.join(tmpDir, '.git-worktree');
      await fs.mkdir(path.join(actualGitDir, 'info'), { recursive: true });
      await fs.writeFile(
        path.join(tmpDir, '.git'),
        `gitdir: ${actualGitDir}\n`,
      );
      await fs.writeFile(
        path.join(actualGitDir, 'info', 'exclude'),
        [
          '# START Ruler Generated Files',
          '/CLAUDE.md',
          '# END Ruler Generated Files',
          '',
        ].join('\n'),
      );
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Claude content');

      await revertAllAgentConfigs(
        tmpDir,
        ['claude'],
        undefined,
        false,
        false,
        false,
      );

      await expect(fs.access(path.join(tmpDir, 'CLAUDE.md'))).rejects.toThrow();
    });
  });

  describe('dry-run logging patterns', () => {
    beforeEach(() => {
      jest.clearAllMocks();
    });

    it('should use [ruler:dry-run] prefix consistently when dryRun is true', async () => {
      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Generated content');

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        true,
      ); // dryRun=true

      const logCalls = consoleLogSpy.mock.calls.flat();
      const hasRulerDryRunPrefix = logCalls.some(
        (call) => typeof call === 'string' && call.includes('[ruler:dry-run]'),
      );

      expect(hasRulerDryRunPrefix).toBe(true);
      consoleLogSpy.mockRestore();
    });

    it('should use [ruler] prefix consistently when dryRun is false', async () => {
      const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation();
      await fs.writeFile(path.join(tmpDir, 'CLAUDE.md'), 'Generated content');

      await revertAllAgentConfigs(
        tmpDir,
        undefined,
        undefined,
        false,
        false,
        false,
      ); // dryRun=false

      const logCalls = consoleLogSpy.mock.calls.flat();
      const hasRulerPrefix = logCalls.some(
        (call) =>
          typeof call === 'string' &&
          call.includes('[ruler]') &&
          !call.includes('[ruler:dry-run]'),
      );

      expect(hasRulerPrefix).toBe(true);
      consoleLogSpy.mockRestore();
    });
  });
});
