import { promises as fs } from 'fs';
import * as path from 'path';
import os from 'os';

import { JcodeAgent } from '../../../src/agents/JcodeAgent';

describe('JcodeAgent', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-jcode-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  const expectedMarker = '<!-- Generated by Ruler -->\n';

  describe('Basic Agent Interface', () => {
    it('returns correct identifier', () => {
      const agent = new JcodeAgent();
      expect(agent.getIdentifier()).toBe('jcode');
    });

    it('returns correct display name', () => {
      const agent = new JcodeAgent();
      expect(agent.getName()).toBe('Jcode');
    });

    it('returns correct default output path for AGENTS.md', () => {
      const agent = new JcodeAgent();
      const expected = path.join(tmpDir, 'AGENTS.md');
      expect(agent.getDefaultOutputPath(tmpDir)).toBe(expected);
    });
  });

  describe('File Operations', () => {
    it('writes AGENTS.md with marker comment', async () => {
      const agent = new JcodeAgent();
      const target = path.join(tmpDir, 'AGENTS.md');

      const sampleRules = 'Sample concatenated rules';

      await agent.applyRulerConfig(sampleRules, tmpDir, null);

      const written = await fs.readFile(target, 'utf8');

      expect(written.startsWith(expectedMarker)).toBe(true);
      expect(written).toBe(`${expectedMarker}${sampleRules}`);
    });

    it('backs up existing file before writing', async () => {
      const agent = new JcodeAgent();
      const target = path.join(tmpDir, 'AGENTS.md');

      await fs.writeFile(target, 'old jcode rules');

      await agent.applyRulerConfig('new jcode rules', tmpDir, null);

      const backupContent = await fs.readFile(`${target}.bak`, 'utf8');
      expect(backupContent).toBe('old jcode rules');
    });

    it('is idempotent when content is unchanged', async () => {
      const agent = new JcodeAgent();
      const target = path.join(tmpDir, 'AGENTS.md');
      const sampleRules = 'Sample rules content';

      await agent.applyRulerConfig(sampleRules, tmpDir, null);
      const stat1 = await fs.stat(target);

      await new Promise((resolve) => setTimeout(resolve, 10));

      await agent.applyRulerConfig(sampleRules, tmpDir, null);
      const stat2 = await fs.stat(target);

      expect(stat2.mtimeMs).toBe(stat1.mtimeMs);
    });
  });

  describe('MCP Support', () => {
    it('supports MCP stdio', () => {
      const agent = new JcodeAgent();
      expect(agent.supportsMcpStdio()).toBe(true);
    });

    it('does not support MCP remote', () => {
      const agent = new JcodeAgent();
      expect(agent.supportsMcpRemote()).toBe(false);
    });

    it('uses mcpServers key', () => {
      const agent = new JcodeAgent();
      expect(agent.getMcpServerKey()).toBe('mcpServers');
    });
  });

  describe('Skills Support', () => {
    it('supports native skills', () => {
      const agent = new JcodeAgent();
      expect(agent.supportsNativeSkills()).toBe(true);
    });
  });
});
