import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';
import { AmazonQCliAgent } from '../../../src/agents/AmazonQCliAgent';
import { CrushAgent } from '../../../src/agents/CrushAgent';
import { MistralVibeAgent } from '../../../src/agents/MistralVibeAgent';
import { ZedAgent } from '../../../src/agents/ZedAgent';
import { IAgent } from '../../../src/agents/IAgent';

const GENERATED_MARKER = '<!-- Generated by Ruler -->';

describe('internal MCP sidecar provenance', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ruler-mcp-prov-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  const cases: Array<{
    agent: () => IAgent;
    provenancePath: string;
  }> = [
    {
      agent: () => new ZedAgent(),
      provenancePath: path.join('.zed', 'settings.json.ruler-generated'),
    },
    {
      agent: () => new AmazonQCliAgent(),
      provenancePath: path.join('.amazonq', 'mcp.json.ruler-generated'),
    },
    {
      agent: () => new CrushAgent(),
      provenancePath: '.crush.json.ruler-generated',
    },
    {
      agent: () => new MistralVibeAgent(),
      provenancePath: path.join('.vibe', 'config.toml.ruler-generated'),
    },
  ];

  it.each(cases)(
    '$provenancePath is created for newly-created internal MCP sidecars',
    async ({ agent, provenancePath }) => {
      await agent().applyRulerConfig(
        '# Rules',
        tmpDir,
        { mcpServers: { test: { command: 'echo' } } },
        undefined,
        false,
      );

      await expect(
        fs.readFile(path.join(tmpDir, provenancePath), 'utf8'),
      ).resolves.toContain(GENERATED_MARKER);
    },
  );
});
