import { RooCodeAgent } from '../../../src/agents/RooCodeAgent';
import { promises as fs } from 'fs';
import { mkdtemp } from 'fs/promises';
import * as os from 'os';
import * as path from 'path';

describe('RooCodeAgent Unit Tests', () => {
  let agent: RooCodeAgent;
  let tmpDir: string;

  beforeEach(async () => {
    agent = new RooCodeAgent();
    tmpDir = await mkdtemp(path.join(os.tmpdir(), 'roo-agent-test-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  describe('Basic Properties', () => {
    it('returns correct identifier', () => {
      expect(agent.getIdentifier()).toBe('roo');
    });

    it('returns correct name', () => {
      expect(agent.getName()).toBe('RooCode');
    });

    it('returns correct default output paths', () => {
      const paths = agent.getDefaultOutputPath('/tmp/test');
      expect(paths.instructions).toBe('/tmp/test/AGENTS.md');
      expect(paths.mcp).toBe('/tmp/test/.roo/mcp.json');
    });

    it('supports MCP stdio', () => {
      expect(agent.supportsMcpStdio()).toBe(true);
    });

    it('supports MCP remote', () => {
      expect(agent.supportsMcpRemote()).toBe(true);
    });

    it('returns correct MCP server key', () => {
      expect(agent.getMcpServerKey()).toBe('mcpServers');
    });

    it('supports native skills', () => {
      expect(agent.supportsNativeSkills()).toBe(true);
    });
  });

  describe('applyRulerConfig', () => {
    it('writes instructions and MCP config to custom paths', async () => {
      const customInstructionsPath = path.join(
        tmpDir,
        'custom',
        'ROO_RULES.md',
      );
      const customMcpPath = path.join(tmpDir, 'settings', 'roo-mcp.json');
      const mcpJson = {
        mcpServers: {
          filesystem: {
            command: 'npx',
            args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
          },
        },
      };

      await agent.applyRulerConfig(
        'Use focused tests',
        tmpDir,
        mcpJson,
        {
          outputPathInstructions: customInstructionsPath,
          outputPathConfig: customMcpPath,
        },
        false,
      );

      await expect(fs.access(path.join(tmpDir, 'AGENTS.md'))).rejects.toThrow();
      await expect(
        fs.access(path.join(tmpDir, '.roo', 'mcp.json')),
      ).rejects.toThrow();
      await expect(
        fs.access(path.join(tmpDir, 'custom', 'ROO_RULES.md.bak')),
      ).rejects.toThrow();
      await expect(fs.access(`${customMcpPath}.bak`)).rejects.toThrow();

      await expect(fs.readFile(customInstructionsPath, 'utf8')).resolves.toBe(
        '<!-- Generated by Ruler -->\nUse focused tests',
      );
      await expect(readJson(customMcpPath)).resolves.toEqual(mcpJson);
    });

    it('falls back to a fresh MCP config when existing JSON is invalid', async () => {
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      await fs.mkdir(path.dirname(mcpPath), { recursive: true });
      await fs.writeFile(mcpPath, '{ invalid json', 'utf8');

      await agent.applyRulerConfig(
        'rules',
        tmpDir,
        {
          mcpServers: {
            context7: { command: 'npx', args: ['-y', '@upstash/context7-mcp'] },
          },
        },
        undefined,
        false,
      );

      await expect(readJson(mcpPath)).resolves.toEqual({
        mcpServers: {
          context7: { command: 'npx', args: ['-y', '@upstash/context7-mcp'] },
        },
      });
      await expect(fs.access(`${mcpPath}.bak`)).rejects.toThrow();
    });

    it('merges new MCP servers with existing servers', async () => {
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      await fs.mkdir(path.dirname(mcpPath), { recursive: true });
      await fs.writeFile(
        mcpPath,
        JSON.stringify(
          {
            mcpServers: {
              existing: { command: 'existing-command' },
            },
          },
          null,
          2,
        ),
      );

      await agent.applyRulerConfig(
        'rules',
        tmpDir,
        {
          mcpServers: {
            added: { command: 'added-command' },
          },
        },
        undefined,
        false,
      );

      await expect(readJson(mcpPath)).resolves.toEqual({
        mcpServers: {
          existing: { command: 'existing-command' },
          added: { command: 'added-command' },
        },
      });
    });

    it('overwrites existing MCP servers with the same name', async () => {
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      await fs.mkdir(path.dirname(mcpPath), { recursive: true });
      await fs.writeFile(
        mcpPath,
        JSON.stringify(
          {
            mcpServers: {
              shared: { command: 'old-command', args: ['old'] },
              untouched: { command: 'keep-command' },
            },
          },
          null,
          2,
        ),
      );

      await agent.applyRulerConfig(
        'rules',
        tmpDir,
        {
          mcpServers: {
            shared: { command: 'new-command', args: ['new'] },
          },
        },
        undefined,
        false,
      );

      await expect(readJson(mcpPath)).resolves.toEqual({
        mcpServers: {
          shared: { command: 'new-command', args: ['new'] },
          untouched: { command: 'keep-command' },
        },
      });
    });

    it('keeps existing MCP servers when no MCP config is provided', async () => {
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      const existingConfig = {
        mcpServers: {
          existing: { command: 'existing-command' },
        },
      };
      await fs.mkdir(path.dirname(mcpPath), { recursive: true });
      await fs.writeFile(mcpPath, JSON.stringify(existingConfig, null, 2));

      await agent.applyRulerConfig('rules', tmpDir, null, undefined, false);

      await expect(readJson(mcpPath)).resolves.toEqual(existingConfig);
    });

    it('creates an empty MCP config when no MCP config or existing servers are available', async () => {
      await agent.applyRulerConfig('rules', tmpDir, null, undefined, false);

      await expect(
        readJson(path.join(tmpDir, '.roo', 'mcp.json')),
      ).resolves.toEqual({
        mcpServers: {},
      });
    });

    it('does not create backups when backup is disabled', async () => {
      const instructionsPath = path.join(tmpDir, 'AGENTS.md');
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      await fs.mkdir(path.dirname(mcpPath), { recursive: true });
      await fs.writeFile(instructionsPath, 'old instructions', 'utf8');
      await fs.writeFile(
        mcpPath,
        JSON.stringify(
          { mcpServers: { old: { command: 'old-command' } } },
          null,
          2,
        ),
      );

      await agent.applyRulerConfig(
        'new instructions',
        tmpDir,
        { mcpServers: { new: { command: 'new-command' } } },
        undefined,
        false,
      );

      await expect(fs.access(`${instructionsPath}.bak`)).rejects.toThrow();
      await expect(fs.access(`${mcpPath}.bak`)).rejects.toThrow();
      await expect(fs.readFile(instructionsPath, 'utf8')).resolves.toBe(
        '<!-- Generated by Ruler -->\nnew instructions',
      );
      await expect(readJson(mcpPath)).resolves.toEqual({
        mcpServers: {
          old: { command: 'old-command' },
          new: { command: 'new-command' },
        },
      });
    });

    it('skips MCP backup and write when config content is unchanged', async () => {
      const mcpPath = path.join(tmpDir, '.roo', 'mcp.json');
      const mcpJson = {
        mcpServers: {
          stable: { command: 'stable-command' },
        },
      };

      await agent.applyRulerConfig('rules', tmpDir, mcpJson);
      const originalMcpStat = await fs.stat(mcpPath);

      await new Promise((resolve) => setTimeout(resolve, 20));
      await agent.applyRulerConfig('updated rules', tmpDir, mcpJson);

      const updatedMcpStat = await fs.stat(mcpPath);
      expect(updatedMcpStat.mtimeMs).toBe(originalMcpStat.mtimeMs);
      await expect(fs.access(`${mcpPath}.bak`)).rejects.toThrow();
    });
  });
});

async function readJson(filePath: string): Promise<unknown> {
  return JSON.parse(await fs.readFile(filePath, 'utf8'));
}
